[build]
builder = "nixpacks"
buildCommand = "npm install && cp prisma/schema.production.prisma prisma/schema.prisma && npx prisma generate && npx prisma db push && npm run build"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
